name: ai_chat_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  dart_openai: ^4.0.0
  equatable: ^2.0.5
  meta: ^1.9.1
  rxdart: ^0.27.7
  uuid: ^3.0.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.21.0
