name: DashGPT Test Pipeline
run-name: Test DashGPT
on: [push]
jobs:
  DashGPT-Test:
    runs-on: ubuntu-latest
    steps:
      - run: cd ./packages/ai_chat_repository/
      - run: dart test
      - run: cd ../../
      - run: flutter test